path_home: "{{ ansible_env.HOME }}"
path_projects: "{{ path_home }}/Projects"
path_dotfiles: "{{ path_projects }}/Dot-Files"

path_wallpaper: /System/Library/Desktop Pictures/Solar Gradients.heic


git_dotfiles: https://github.com/ggustafsson/Dot-Files.git
git_staticcolorscheme: https://github.com/ggustafsson/Static-Color-Scheme.git


brew_macos:
  - bash
  - coreutils
  - curl
  - dialog
  - figlet
  - fzf
  - git
  - golang
  - grep
  - html2text
  - less
  - links
  - neovim
  - nmap
  - openssh
  - python
  - renameutils
  - ripgrep
  - rsync
  - ruby
  - shellcheck
  - tidy-html5
  - tmux
  - tree
  - vim
  - wget
  - zsh
  - zsh-autosuggestions

brew_macos_home:
  - cuetools
  - ffmpeg
  - flac
  - imagemagick
  - lame
  - shntool
  - svtplay-dl
  - youtube-dl

#brew_macos_work:
#  - x

cask_macos:
  - docker
  - google-chrome
  - hammerspoon
  - visual-studio-code

cask_macos_home:
  - 1password
  - dropbox
  - handbrake
  - openemu
  - tor-browser
  - transmission
  - vlc

cask_macos_work:
  - slack


apt_ubuntu:
  - dialog
  - dnsutils
  - figlet
  - flac
  - golang
  - html2text
  - links
  - nmap
  - python3-pip
  - ripgrep
  - ruby
  - shellcheck
  - tidy
  - tree
  - zsh

apt_ubuntu_tv:
  - abcde
  - kodi
  - sshguard

#apt_ubuntu_vm:
#  - x


linuxbrew:
  - fzf
  - neovim
  - vim
  - zsh-autosuggestions

#linuxbrew_ubuntu:
#  - x

#linuxbrew_ubuntu_tv:
#  - x

#linuxbrew_ubuntu_vm:
#  - x


pip_macos:
  - ansible
  - ansible-lint
  - docker
  - flake8
  - pip

#pip_macos_home:
#  - x

#pip_macos_work:
#  - x

pip_linux:
  - ansible
  - ansible-lint
  - flake8
  - pip

pip_ubuntu: "{{ pip_linux }}"

#pip_ubuntu_tv:
#  - x

#pip_ubuntu_vm:
#  - x
