- name: Install Homebrew packages from list 'brew_macos_work'
  community.general.homebrew:
    name: "{{ brew_macos_work }}"
    state: latest
  when: brew_macos_work is defined

- name: Install Homebrew applications from list 'cask_macos_work'
  community.general.homebrew_cask:
    name: "{{ cask_macos_work }}"
    state: latest
    install_options: appdir=~/Applications
  when: cask_macos_work is defined

- name: Install Pip packages from list 'pip_macos_work'
  ansible.builtin.pip:
    name: "{{ pip_macos_work }}"
    state: latest
    executable: "{{ pip_exec }}"
  when: pip_macos_work is defined


- name: Create misc directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - "{{ path_home }}/Git"
