- name: Setup macOS system - Home
  hosts: macos
  # TODO: Adjust hostname line after getting new MacBook Pro.
  vars:
    hostname: Coruscant
  roles:
    - common
    - macos
    - macos_home
    - vim
