- name: Setup macOS system - Work
  hosts: macos
  vars:
    hostname: Twoson
    git_dotfiles: https://github.com:ggustafsson/Dot-Files.git
    git_staticcolorscheme: https://github.com:ggustafsson/Static-Color-Scheme.git
  roles:
    - common
    - macos
    - macos_work
    - common_vim
