- name: Generate help tags for all plugins
  ansible.builtin.command:
    cmd: nvim -c 'helptags ALL' -c q
  listen: Generate help tags
  changed_when: true

- name: Update all Treesitter parsers
  ansible.builtin.command:
    cmd: nvim -c 'TSUpdateSync' -c q
  listen: Update Treesitter parsers
  changed_when: true
