---
- name: Upgrade all packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
  become: yes

- name: Install misc packages
  ansible.builtin.apt:
    pkg:
      - ansible
      - dnsutils
      - flac
      - golang
      - html2text
      - links
      - nmap
      - ruby
      - tree
      - zsh
    state: latest
    update_cache: yes
  become: yes

- name: Copy AllowUsers.conf to /etc/ssh/sshd_config.d
  ansible.builtin.template:
    src: sshd_config.d/AllowUsers.conf.j2
    dest: /etc/ssh/sshd_config.d/AllowUsers.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - Restart sshd
