- name: Upgrade all APT packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
  become: yes
  register: apt

- name: "Upgrade all APT packages : debug"
  ansible.builtin.debug:
    var: apt.stdout

- name: Install misc APT packages
  ansible.builtin.apt:
    pkg:
      - dialog
      - dnsutils
      - figlet
      - flac
      - fzf
      - golang
      - html2text
      - links
      - nmap
      - python3-pip
      - ruby
      - shellcheck
      - silversearcher-ag
      - tidy
      - tree
      - zsh
    state: latest
  become: yes
  register: apt

- name: "Install misc APT packages : debug"
  ansible.builtin.debug:
    var: apt.stdout

- name: Install misc Pip packages
  ansible.builtin.pip:
    name:
      - ansible
      - ansible-lint
      - flake8
      - pip
    state: latest
  register: pip

# FIXME: ansible.builtin.pip only returns useless info...
- name: "Install misc Pip packages : debug"
  ansible.builtin.debug:
    var: pip.name


- name: Create misc symbolic links
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: /usr/share/doc/fzf/examples
      dest: "{{ path_home }}/.vim/pack/others/start/fzf"
    - src: /usr/share/doc/fzf/examples
      dest: "{{ path_home }}/.zsh/fzf"

- name: Create file /etc/ssh/sshd_config.d/AllowUsers.conf
  ansible.builtin.template:
    src: sshd_config.d/AllowUsers.conf.j2
    dest: /etc/ssh/sshd_config.d/AllowUsers.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart sshd
