- name: Upgrade all APT packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
  become: yes
  register: apt

- name: Install misc APT packages
  ansible.builtin.apt:
    pkg: "{{ apt_ubuntu }}"
    state: latest
  become: yes
  register: apt

- name: Install misc Pip packages
  ansible.builtin.pip:
    name: "{{ pip_ubuntu }}"
    state: latest
  register: pip


- name: Create file /etc/ssh/sshd_config.d/AllowUsers.conf
  ansible.builtin.template:
    src: sshd_config.d/AllowUsers.conf.j2
    dest: /etc/ssh/sshd_config.d/AllowUsers.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart sshd
