- name: Upgrade all APT packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
  become: yes
  register: apt

- name: "Upgrade all APT packages : debug"
  ansible.builtin.debug:
    var: apt.stdout

- name: Install misc APT packages
  ansible.builtin.apt:
    pkg:
      - dialog
      - dnsutils
      - figlet
      - flac
      - golang
      - html2text
      - links
      - nmap
      - ruby
      - shellcheck
      - tidy
      - tree
      - zsh
    state: latest
  become: yes
  register: apt

- name: "Install misc APT packages : debug"
  ansible.builtin.debug:
    var: apt.stdout

- name: Create file /etc/ssh/sshd_config.d/AllowUsers.conf
  ansible.builtin.template:
    src: sshd_config.d/AllowUsers.conf.j2
    dest: /etc/ssh/sshd_config.d/AllowUsers.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart sshd
