- name: Upgrade all APT packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
  become: yes

- name: Install APT packages from list 'apt_ubuntu'
  ansible.builtin.apt:
    pkg: "{{ apt_ubuntu }}"
    state: latest
  become: yes
  when: apt_ubuntu is defined

- name: Install Linuxbrew packages from list 'linuxbrew_ubuntu'
  community.general.homebrew:
    name: "{{ linuxbrew_ubuntu }}"
    state: latest
  when: linuxbrew_ubuntu is defined

- name: Install Pip packages from list 'pip_ubuntu'
  ansible.builtin.pip:
    name: "{{ pip_ubuntu }}"
    state: latest
  when: pip_ubuntu is defined


- name: Create file /etc/ssh/sshd_config.d/AllowUsers.conf
  ansible.builtin.template:
    src: sshd_config.d/AllowUsers.conf.j2
    dest: /etc/ssh/sshd_config.d/AllowUsers.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart sshd
