- name: Install Linuxbrew at {{ path_linuxbrew }}
  block:
    - name: Get stats on {{ path_linuxbrew }}
      ansible.builtin.stat:
        path: "{{ path_linuxbrew }}"
      register: stat_linuxbrew

    - name: Fetching https://api.github.com/repos/Homebrew/brew/releases/latest
      ansible.builtin.uri:
        url: https://api.github.com/repos/Homebrew/brew/releases/latest
        return_content: yes
      register: release
      failed_when: release.json.tarball_url is not defined

    - name: Fetching {{ release.json.tarball_url }}
      ansible.builtin.get_url:
        url: "{{ release.json.tarball_url }}"
        dest: "{{ path_tarball }}"

    - name: Extract file {{ path_tarball }}
      ansible.builtin.unarchive:
        src: "{{ path_tarball }}"
        dest: /tmp
        remote_src: yes
        list_files: yes
      register: unarchive

    - name: Copy /tmp/{{ unarchive.files[0] }} to {{ path_linuxbrew }}
      ansible.builtin.copy:
        src: /tmp/{{ unarchive.files[0] }}
        dest: "{{ path_linuxbrew }}"
        remote_src: yes
        mode: 0700
  when: stat_linuxbrew.stat.isdir is not defined

- name: Upgrade all Linuxbrew packages
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install Linuxbrew packages from list 'linuxbrew'
  community.general.homebrew:
    name: "{{ linuxbrew }}"
    state: latest
  when: linuxbrew is defined


- name: Create misc symbolic links
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ path_home }}/.linuxbrew/opt/fzf"
      dest: "{{ path_home }}/.local/share/fzf"
