- name: Add public SSH keys to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{% for key in query('fileglob', 'ssh/id_*.pub') %}{{ lookup('file', key) ~ '\n' }}{% endfor %}"
    state: present
    exclusive: true


- name: Create directory {{ path_linuxbrew }}
  ansible.builtin.file:
    path: "{{ path_linuxbrew }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0700
  become: true

- name: Git clone/pull Linuxbrew repos
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop:
    - repo: https://github.com/Homebrew/brew.git
      dest: "{{ path_linuxbrew }}"
    - repo: https://github.com/Homebrew/homebrew-core
      dest: "{{ path_linuxbrew }}/Library/Taps/homebrew/homebrew-core"

- name: Upgrade all Linuxbrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
    path: "{{ path_linuxbrew }}/bin"

- name: Install Linuxbrew packages from list 'linuxbrew_linux'
  community.general.homebrew:
    name: "{{ linuxbrew_linux }}"
    state: latest
    path: "{{ path_linuxbrew }}/bin"
  when: linuxbrew_linux is defined


- name: Create misc symbolic links
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ path_linuxbrew }}/opt/fzf"
      dest: "{{ path_home }}/.local/share/fzf"
    - src: "{{ path_linuxbrew }}/opt/zsh-autosuggestions/share/zsh-autosuggestions"
      dest: "{{ path_home }}/.local/share/zsh-autosuggestions"
