- name: Add id_ed25519.pub to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    key: id_ed25519.pub
    state: present
    exclusive: true


- name: Get stats on {{ path_linuxbrew }}/bin/brew
  ansible.builtin.stat:
    path: "{{ path_linuxbrew }}/bin/brew"
  register: brew_bin

- name: Install Linuxbrew at {{ path_linuxbrew }}
  block:
    - name: Fetching https://api.github.com/repos/Homebrew/brew/releases/latest
      ansible.builtin.uri:
        url: https://api.github.com/repos/Homebrew/brew/releases/latest
        return_content: true
      register: release
      failed_when: release.json.tarball_url is not defined

    - name: Fetching {{ release.json.tarball_url }}
      ansible.builtin.get_url:
        url: "{{ release.json.tarball_url }}"
        dest: "{{ path_linuxbrew_tar }}"
      when: release.json.tarball_url is defined

    - name: Extract file {{ path_linuxbrew_tar }}
      ansible.builtin.unarchive:
        src: "{{ path_linuxbrew_tar }}"
        dest: /tmp
        remote_src: true
        list_files: true
      register: unarchive
      when: release.json.tarball_url is defined

    - name: Copy /tmp/{{ unarchive.files[0] }} to {{ path_linuxbrew }}
      ansible.builtin.copy:
        src: /tmp/{{ unarchive.files[0] }}
        dest: "{{ path_linuxbrew }}"
        remote_src: true
        mode: 0700
      when: unarchive.changed
  when: brew_bin.stat.exists == false

- name: Upgrade all Linuxbrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
    path: "{{ path_linuxbrew }}/bin"

- name: Install Linuxbrew packages from list 'linuxbrew_linux'
  community.general.homebrew:
    name: "{{ linuxbrew_linux }}"
    state: latest
    path: "{{ path_linuxbrew }}/bin"
  when: linuxbrew_linux is defined


- name: Create misc symbolic links
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ path_linuxbrew }}/opt/fzf"
      dest: "{{ path_home }}/.local/share/fzf"
    - src: "{{ path_linuxbrew }}/opt/zsh-autosuggestions/share/zsh-autosuggestions"
      dest: "{{ path_home }}/.zsh/zsh-autosuggestions"
