---
- name: Copy file to /etc/motd
  ansible.builtin.copy:
    remote_src: yes
    src: "{{ projects_dir }}/Dot-Files/motd"
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  become: yes
