---
- name: Print debug info
  ansible.builtin.debug:
    msg:
      - "ansible_env.USER is {{ ansible_env.USER }}"

- name: Set {{ ansible_env.HOME }} & ~/.ssh directory permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0700
  loop:
    - "{{ ansible_env.HOME }}"
    - "{{ ansible_env.HOME }}/.ssh"

- name: Create directory {{ ansible_env.HOME }}/Projects
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Projects"
    state: directory

- name: Git clone {{ git_url_dotfiles }}
  ansible.builtin.git:
    repo: "{{ git_url_dotfiles }}"
    dest: "{{ ansible_env.HOME }}/Projects/Dot-Files"
    update: yes
