- name: Create directory {{ path_home }}/Applications
  ansible.builtin.file:
    path: "{{ path_home }}/Applications"
    state: directory
    mode: 0700

- name: Create file /etc/sudoers.d/custom
  ansible.builtin.template:
    src: sudoers.d/custom.j2
    dest: /etc/sudoers.d/custom
    owner: root
    group: wheel
    mode: 0640
  become: true

- name: Git clone/pull misc projects
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ path_projects }}/{{ item.name }}"
  loop:
    - name: electricboogaloo.16colors
      url: "{{ git_electricboogaloo_16colors }}"
    - name: Project-Assets
      url: "{{ git_projectassets }}"
    - name: Tim
      url: "{{ git_tim }}"


- name: Get stats on {{ path_homebrew }}/bin/brew
  ansible.builtin.stat:
    path: "{{ path_homebrew }}/bin/brew"
  register: brew_bin

- name: Install Homebrew at {{ path_homebrew }}
  block:
    - name: Fetching https://api.github.com/repos/Homebrew/brew/releases/latest
      ansible.builtin.uri:
        url: https://api.github.com/repos/Homebrew/brew/releases/latest
        return_content: true
      register: release
      failed_when: release.json.zipball_url is not defined

    - name: Fetching {{ release.json.zipball_url }}
      ansible.builtin.get_url:
        url: "{{ release.json.zipball_url }}"
        dest: "{{ path_homebrew_zip }}"
      when: release.json.zipball_url is defined

    - name: Extract file {{ path_homebrew_zip }}
      ansible.builtin.unarchive:
        src: "{{ path_homebrew_zip }}"
        dest: /tmp
        remote_src: true
        list_files: true
      register: unarchive
      when: release.json.zipball_url is defined

    - name: Copy /tmp/{{ unarchive.files[0] }} to {{ path_homebrew }}
      ansible.builtin.copy:
        src: /tmp/{{ unarchive.files[0] }}
        dest: "{{ path_homebrew }}"
        remote_src: true
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: 0700
      become: true
      when: unarchive.changed
  when: brew_bin.stat.exists == false

- name: Upgrade all Homebrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install Homebrew packages from list 'brew_macos'
  community.general.homebrew:
    name: "{{ brew_macos }}"
    state: latest
  when: brew_macos is defined

- name: Install Homebrew applications from list 'cask_macos'
  community.general.homebrew_cask:
    name: "{{ cask_macos }}"
    state: latest
    install_options: appdir=~/Applications
  when: cask_macos is defined

- name: Install Pip packages from list 'pip_common'
  ansible.builtin.pip:
    name: "{{ pip_common }}"
    state: latest
    executable: "{{ pip_exec }}"
  when: pip_common is defined

- name: Install Pip packages from list 'pip_macos'
  ansible.builtin.pip:
    name: "{{ pip_macos }}"
    state: latest
    executable: "{{ pip_exec }}"
  when: pip_macos is defined


- name: Create directory {{ path_home }}/.terminfo/74
  ansible.builtin.file:
    path: "{{ path_home }}/.terminfo/74"
    state: directory
    mode: 0700

- name: Create misc symbolic links
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ path_homebrew }}/bin/ggrep"
      dest: "{{ path_homebrew }}/bin/grep"
    - src: "{{ path_homebrew }}/bin/gls"
      dest: "{{ path_homebrew }}/bin/ls"
    - src: "{{ path_homebrew }}/opt/fzf"
      dest: "{{ path_home }}/.local/share/fzf"
    - src: "{{ path_homebrew }}/opt/zsh-autosuggestions/share/zsh-autosuggestions"
      dest: "{{ path_home }}/.zsh/zsh-autosuggestions"
    - src: "{{ path_dotfiles }}/Misc/Swedish-Pro-No_Dead_Keys.bundle"
      dest: "{{ path_home }}/Library/Keyboard Layouts/Swedish-Pro-No_Dead_Keys.bundle"
    - src: "{{ path_dotfiles }}/Misc/tmux-256color"
      dest: "{{ path_home }}/.terminfo/74/tmux-256color"
    - src: "{{ path_projects }}/Tim/tim"
      dest: "{{ path_home }}/Scripts/tim"

- name: Add {{ path_homebrew }}/bin/zsh to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ path_homebrew }}/bin/zsh"


- name: Execute misc 'defaults' and 'chflags' commands
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - chflags nohidden ~/Library
  changed_when: false

- name: Check desktop wallpaper
  ansible.builtin.command:
    cmd: sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "SELECT value FROM data ORDER BY ROWID DESC LIMIT 1"
  register: dock_wallpaper
  changed_when: false

- name: Set desktop wallpaper
  ansible.builtin.command:
    cmd: sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "{{ item }}"
  loop:
    - DELETE FROM data
    - DELETE FROM pictures
    - DELETE FROM preferences
    - "INSERT INTO data (value) VALUES ('{{ path_wallpaper }}')"
    - INSERT INTO preferences (key, data_id, picture_id) VALUES (1, 1, 1)
  notify: restart dock
  when: path_wallpaper not in dock_wallpaper.stdout

- name: Check keyboard layout
  ansible.builtin.command:
    cmd: defaults read com.apple.HIToolbox AppleEnabledInputSources
  register: defaults_read
  changed_when: false

# FIXME: Finish and verify after moving over to new MacBook Pro.
- name: Set keyboard layout
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    #- defaults write com.apple.HIToolbox AppleCurrentKeyboardLayoutInputSourceID -string org.sil.ukelele.keyboardlayout.swedish-pro-nodeadkeys.swedish-pro-nodeadkeys
    - defaults write com.apple.HIToolbox AppleEnabledInputSources -array-add '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>-24875</integer><key>KeyboardLayout Name</key><string>Swedish - Pro - No Dead Keys</string></dict>'
    #- defaults write com.apple.HIToolbox AppleSelectedInputSources -array '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>-24875</integer><key>KeyboardLayout Name</key><string>Swedish - Pro - No Dead Keys</string></dict>'
    #- defaults write com.apple.HIToolbox AppleSelectedInputSources -array-add '<dict><key>Bundle ID</key><string>com.apple.PressAndHold</string><key>InputSourceKind</key><string>Non Keyboard Input Method</string></dict>'
  when: '"Swedish - Pro - No Dead Keys" not in defaults_read.stdout'
