- name: Create file /etc/sudoers.d/custom
  ansible.builtin.template:
    src: sudoers.d/custom.j2
    dest: /etc/sudoers.d/custom
    owner: root
    group: wheel
    mode: 0640
  become: yes

# FIXME: Install Xcode Command Line Tools.

# FIXME: Install Homebrew.
#- name: Set directory permission /opt/homebrew
#  ansible.builtin.file:
#    path: "/opt/homebrew"
#    state: directory
#    owner: "{{ ansible_env.USER }}"
#    mode: 0700
#  become: yes
#
#  ...

- name: Create directory {{ ansible_env.HOME }}/Applications
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Applications"
    state: directory
    mode: 0700

- name: Upgrade all packages
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes
  register: brew

- name: "Upgrade all packages : debug"
  debug: var=brew.changed_pkgs

- name: Install misc packages
  community.general.homebrew:
    name:
      - ansible
      - ansible-lint
      - bash
      - coreutils
      - curl
      - flake8
      - git
      - golang
      - grep
      - html2text
      - less
      - links
      - neovim
      - nmap
      - openssh
      - pylint
      - python
      - renameutils
      - rsync
      - ruby
      - shellcheck
      - tidy-html5
      - tmux
      - tree
      - vim
      - wget
      - yamllint
      - zsh
    state: latest
  register: brew

- name: "Install misc packages : debug"
  debug: var=brew.changed_pkgs

- name: Install misc applications
  community.general.homebrew_cask:
    name:
      - docker
      - google-chrome
      - hammerspoon
      - visual-studio-code
    state: latest
    install_options: "appdir=~/Applications"
  register: brew

- name: "Install misc applications : debug"
  debug: var=brew.msg

# TODO: Enable after moving over to new MacBook Pro.
#- name: Add /opt/homebrew/bin/zsh to /etc/shells
#  ansible.builtin.lineinfile:
#    path: /etc/shells
#    line: /opt/homebrew/bin/zsh
#
#- name: Create misc symbolic links
#  ansible.builtin.file:
#    src: "/opt/homebrew/bin/{{ item.src }}"
#    dest: "/opt/homebrew/bin/{{ item.dest }}"
#    state: link
#  loop:
#    - src: ggrep
#      dest: grep
#    - src: gls
#      dest: ls

- name: Create directory {{ ansible_env.HOME }}/.terminfo/74
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.terminfo/74"
    state: directory
    mode: 0700

- name: Create symbolic link {{ ansible_env.HOME }}/.terminfo/74/tmux-256color
  ansible.builtin.file:
    src: "{{ projects_dir }}/Dot-Files/Misc/tmux-256color"
    dest: "{{ ansible_env.HOME }}/.terminfo/74/tmux-256color"
    state: link

- name: Execute misc 'defaults' and 'chflags' commands
  ansible.builtin.command:
    cmd: "{{ item.cmd }}"
  loop:
    - cmd: chflags nohidden ~/Library
    - cmd: defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
  changed_when: False
