- name: Upgrade all Pacman packages
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: yes
  register: pacman

- name: Install misc Pacman packages
  community.general.pacman:
    pkg: "{{ pacman_arch }}"
    state: latest
  become: yes
  register: pacman

- name: Install misc Pip packages
  ansible.builtin.pip:
    name: "{{ pip_arch }}"
    state: latest
  register: pip


- name: Set AllowUsers in /etc/ssh/sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ ansible_env.USER }}"
    validate: /usr/sbin/sshd -T -f %s
  notify: restart sshd
