- name: Upgrade all packages
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: yes
  register: pacman

- name: "Upgrade all packages : debug"
  ansible.builtin.debug:
    var: pacman.packages

# TODO: Adjust and enable after playing around with Docker.
#- name: Install misc packages
#  community.general.pacman:
#    pkg:
#      - x
#    state: latest
#  become: yes
#  register: pacman
#
#- name: "Install misc packages : debug"
#  ansible.builtin.debug:
#    var: pacman.packages

- name: Set AllowUsers in /etc/ssh/sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ ansible_env.USER }}"
    validate: /usr/sbin/sshd -T -f %s
  notify: restart sshd
