- name: Install Homebrew packages from list 'brew_macos_home'
  community.general.homebrew:
    name: "{{ brew_macos_home }}"
    state: latest
  when: brew_macos_home is defined

- name: Install Homebrew applications from list 'cask_macos_home'
  community.general.homebrew_cask:
    name: "{{ cask_macos_home }}"
    state: latest
    install_options: appdir=~/Applications
  when: cask_macos_home is defined

- name: Install Homebrew applications from list 'cask_macos_home_root'
  community.general.homebrew_cask:
    name: "{{ cask_macos_home_root }}"
    state: latest
    install_options: appdir=/Applications
  when: cask_macos_home_root is defined

- name: Install Pip packages from list 'pip_macos_home'
  ansible.builtin.pip:
    name: "{{ pip_macos_home }}"
    state: latest
    executable: "{{ pip_exec }}"
  when: pip_macos_home is defined

- name: Install Go packages from list 'go_macos_home'
  ansible.builtin.shell:
    cmd: GOPATH={{ path_golang | quote }} go install {{ item | quote }}
  loop: "{{ go_macos_home }}"
  when: go_macos_home is defined
  changed_when: false


- name: Create misc directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - "{{ path_home }}/Storage"
