- name: Install Homebrew packages from list 'brew_macos_home'
  community.general.homebrew:
    name: "{{ brew_macos_home }}"
    state: latest
  when: brew_macos_home is defined

- name: Install Homebrew applications from list 'cask_macos_home'
  community.general.homebrew_cask:
    name: "{{ cask_macos_home }}"
    state: latest
    install_options: appdir=~/Applications
  when: cask_macos_home is defined

- name: Install Pip packages from list 'pip_macos_home'
  ansible.builtin.pip:
    name: "{{ pip_macos_home }}"
    state: latest
    executable: "{{ pip_exec }}"
  when: pip_macos_home is defined
