- name: Install misc Homebrew packages
  community.general.homebrew:
    name:
      - cuetools
      - ffmpeg
      - flac
      - imagemagick
      - lame
      - shntool
      - svtplay-dl
      - youtube-dl
    state: latest
  register: brew

- name: "Install misc Homebrew packages : debug"
  ansible.builtin.debug:
    var: brew.changed_pkgs

- name: Install misc Homebrew applications
  community.general.homebrew_cask:
    name:
      - 1password
      - dropbox
      - handbrake
      - openemu
      - tor-browser
      - transmission
      - vlc
    state: latest
    install_options: appdir=~/Applications
  register: brew

- name: "Install misc Homebrew applications : debug"
  ansible.builtin.debug:
    var: brew.msg
