---
- name: Install misc packages
  ansible.builtin.apt:
    pkg:
      - abcde
      - kodi
      - sshguard
    state: latest
    update_cache: yes
  become: yes

- name: Copy Port.conf to /etc/ssh/sshd_config.d
  ansible.builtin.copy:
    src: sshd_config.d/Port.conf
    dest: /etc/ssh/sshd_config.d/Port.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - Restart sshd
