- name: Install misc packages
  ansible.builtin.apt:
    pkg:
      - abcde
      - kodi
      - sshguard
    state: latest
    update_cache: yes
  become: yes

- name: Copy Port.conf to /etc/ssh/sshd_config.d
  ansible.builtin.copy:
    src: sshd_config.d/Port.conf
    dest: /etc/ssh/sshd_config.d/Port.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart sshd

- name: Set AutomaticLogin in /etc/gdm3/custom.conf
  ansible.builtin.lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: yes
  loop:
    - regexp: "^#  AutomaticLoginEnable = true"
      line: "AutomaticLoginEnable = true"
    - regexp: "^#  AutomaticLogin = user1"
      line: "AutomaticLogin = gleg"
