---
- name: Print debug info
  ansible.builtin.debug:
    msg:
      - "ansible_env.USER is {{ ansible_env.USER }}"

- name: Set misc directory permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0700
  loop:
    - "{{ ansible_env.HOME }}"
    - "{{ ansible_env.HOME }}/.ssh"

- name: Set misc file permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: file
    owner: "{{ ansible_env.USER }}"
    mode: 0600
  loop:
    - "{{ ansible_env.HOME }}/.ssh/id_ed25519"

- name: Create directory {{ projects_dir }}
  ansible.builtin.file:
    path: "{{ projects_dir }}"
    state: directory
    mode: 0700

- name: Git clone/pull {{ git_url_dotfiles }}
  ansible.builtin.git:
    repo: "{{ git_url_dotfiles }}"
    dest: "{{ projects_dir }}/Dot-Files"
