- name: Set misc directory permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0700
  loop:
    - "{{ path_home }}"
    - "{{ path_home }}/.ssh"

- name: Get stats on {{ path_home }}/.ssh/id_ed25519
  ansible.builtin.stat:
    path: "{{ path_home }}/.ssh/id_ed25519"
  register: id_ed25519

- name: Set file permissions on {{ path_home }}/.ssh/id_ed25519
  ansible.builtin.file:
    path: "{{ path_home }}/.ssh/id_ed25519"
    state: file
    owner: "{{ ansible_env.USER }}"
    mode: 0600
  when: id_ed25519.stat.exists

- name: Create directory {{ path_projects }}
  ansible.builtin.file:
    path: "{{ path_projects }}"
    state: directory
    mode: 0700

- name: Git clone/pull {{ git_url_dotfiles }}
  ansible.builtin.git:
    repo: "{{ git_url_dotfiles }}"
    dest: "{{ path_dotfiles }}"

- name: Create symbolic links to Dot-Files
  ansible.builtin.file:
    src: "{{ path_dotfiles }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: Scripts
      dest: "{{ path_home }}/Scripts"
    - src: ansible.cfg
      dest: "{{ path_home }}/.ansible.cfg"
    - src: gitconfig
      dest: "{{ path_home }}/.gitconfig"
    - src: gitignore_global
      dest: "{{ path_home }}/.gitignore_global"
    - src: ssh/config
      dest: "{{ path_home }}/.ssh/config"
    - src: tmux.conf
      dest: "{{ path_home }}/.tmux.conf"
    - src: zshenv
      dest: "{{ path_home }}/.zshenv"
    - src: zshrc
      dest: "{{ path_home }}/.zshrc"
