- name: Set hostname to {{ hostname }}
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  become: true
  when: ansible_facts.virtualization_type != "docker"


- name: Set misc directory permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700
  loop:
    - "{{ path_home }}"
    - "{{ path_home }}/.ssh"

- name: Get stats on {{ path_home }}/.ssh/id_ed25519
  ansible.builtin.stat:
    path: "{{ path_home }}/.ssh/id_ed25519"
  register: id_ed25519

- name: Set file permissions on {{ path_home }}/.ssh/id_ed25519
  ansible.builtin.file:
    path: "{{ path_home }}/.ssh/id_ed25519"
    state: file
    owner: "{{ ansible_user_id }}"
    mode: 0600
  when: id_ed25519.stat.exists


- name: Create misc directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - "{{ path_projects }}"
    - "{{ path_home }}/.config"
    - "{{ path_home }}/.config/yamllint"
    - "{{ path_home }}/.local"
    - "{{ path_home }}/.local/bin"
    - "{{ path_home }}/.local/share"
    - "{{ path_home }}/.zsh"
    - "{{ path_home }}/Documents"
    - "{{ path_home }}/Documents/Text"

- name: Git clone/pull misc projects
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ item.name }}"
  loop:
    - name: "{{ path_dotfiles }}"
      url: "{{ git_dotfiles }}"
    - name: "{{ path_projects }}/Tim"
      url: "{{ git_tim }}"

- name: Create misc symbolic links
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ path_dotfiles }}/Scripts"
      dest: "{{ path_home }}/Scripts"
    - src: "{{ path_dotfiles }}/pylintrc"
      dest: "{{ path_home }}/.config/pylintrc"
    - src: "{{ path_dotfiles }}/yamllint"
      dest: "{{ path_home }}/.config/yamllint/config"
    - src: "{{ path_dotfiles }}/figlet"
      dest: "{{ path_home }}/.figlet"
    - src: "{{ path_dotfiles }}/gitconfig"
      dest: "{{ path_home }}/.gitconfig"
    - src: "{{ path_dotfiles }}/gitignore_global"
      dest: "{{ path_home }}/.gitignore_global"
    - src: "{{ path_projects }}/Tim/tim"
      dest: "{{ path_home }}/.local/bin/tim"
    - src: "{{ path_dotfiles }}/ssh/config"
      dest: "{{ path_home }}/.ssh/config"
    - src: "{{ path_dotfiles }}/tmux.conf"
      dest: "{{ path_home }}/.tmux.conf"
    - src: "{{ path_dotfiles }}/zlogin"
      dest: "{{ path_home }}/.zlogin"
    - src: "{{ path_dotfiles }}/zshenv"
      dest: "{{ path_home }}/.zshenv"
    - src: "{{ path_dotfiles }}/zshrc"
      dest: "{{ path_home }}/.zshrc"
