- name: Set misc directory permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0700
  loop:
    - "{{ ansible_env.HOME }}"
    - "{{ ansible_env.HOME }}/.ssh"

- name: Get stats on {{ ansible_env.HOME }}/.ssh/id_ed25519
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
  register: id_ed25519

- name: Set file permissions on {{ ansible_env.HOME }}/.ssh/id_ed25519
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    state: file
    owner: "{{ ansible_env.USER }}"
    mode: 0600
  when: id_ed25519.stat.exists

- name: Create directory {{ projects_dir }}
  ansible.builtin.file:
    path: "{{ projects_dir }}"
    state: directory
    mode: 0700

- name: Git clone/pull {{ git_url_dotfiles }}
  ansible.builtin.git:
    repo: "{{ git_url_dotfiles }}"
    dest: "{{ projects_dir }}/Dot-Files"

- name: Create symbolic links to Dot-Files
  ansible.builtin.file:
    src: "{{ projects_dir }}/Dot-Files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: Scripts
      dest: "{{ ansible_env.HOME }}/Scripts"
    - src: ansible.cfg
      dest: "{{ ansible_env.HOME }}/.ansible.cfg"
    - src: gitconfig
      dest: "{{ ansible_env.HOME }}/.gitconfig"
    - src: gitignore_global
      dest: "{{ ansible_env.HOME }}/.gitignore_global"
    - src: ssh_config
      dest: "{{ ansible_env.HOME }}/.ssh/config"
    - src: tmux.conf
      dest: "{{ ansible_env.HOME }}/.tmux.conf"
    - src: zshenv
      dest: "{{ ansible_env.HOME }}/.zshenv"
    - src: zshrc
      dest: "{{ ansible_env.HOME }}/.zshrc"
