---
- name: Create directory {{ projects_dir }}
  ansible.builtin.file:
    path: "{{ projects_dir }}"
    state: directory

# FIXME: Add git clone of Dot-Files etc...
#- name: Git clone {{ git_url_dotfiles }}
#  ansible.builtin.git:
#    repo: "{{ git_url_dotfiles }}"
#    dest: "{{ projects_dir }}/Dot-Files"
#    update: yes

#- name: Git clone {{ git_url_electricboogaloo }}
#  ansible.builtin.git:
#    repo: "{{ git_url_electricboogaloo }}"
#    dest: "{{ projects_dir }}/electricboogaloo.vim"
#    update: yes

- name: Git clone {{ git_url_staticcolorscheme }}
  ansible.builtin.git:
    repo: "{{ git_url_staticcolorscheme }}"
    dest: "{{ projects_dir }}/Static-Color-Scheme"
    update: yes

- name: Create directory {{ vim_dir }}/backup
  ansible.builtin.file:
    path: "{{ vim_dir }}/backup"
    state: directory

- name: Create directory {{ vim_dir }}/swap
  ansible.builtin.file:
    path: "{{ vim_dir }}/swap"
    state: directory

- name: Create directory {{ vim_dir }}/undo
  ansible.builtin.file:
    path: "{{ vim_dir }}/undo"
    state: directory

- name: Create directory {{ vim_dir }}/pack/ggustafsson/start
  ansible.builtin.file:
    path: "{{ vim_dir }}/pack/ggustafsson/start"
    state: directory

- name: Create directory {{ vim_dir }}/pack/others/start
  ansible.builtin.file:
    path: "{{ vim_dir }}/pack/others/start"
    state: directory

- name: Create symbolic link {{ vim_dir }}rc
  ansible.builtin.file:
    src: "{{ projects_dir }}/Dot-Files/vimrc"
    dest: "{{ vim_dir }}rc"
    state: link

- name: Create symbolic link {{ vim_dir }}/after
  ansible.builtin.file:
    src: "{{ projects_dir }}/Dot-Files/vim/after"
    dest: "{{ vim_dir }}/after"
    state: link

- name: Create symbolic link {{ vim_dir }}/templates
  ansible.builtin.file:
    src: "{{ projects_dir }}/Dot-Files/vim/templates"
    dest: "{{ vim_dir }}/templates"
    state: link

- name: Create symbolic link {{ vim_dir }}/pack/ggustafsson/start/Static-Color-Scheme
  ansible.builtin.file:
    src: "{{ projects_dir }}/Static-Color-Scheme"
    dest: "{{ vim_dir }}/pack/ggustafsson/start/Static-Color-Scheme"
    state: link

- name: Git clone https://github.com/pearofducks/ansible-vim.git
  ansible.builtin.git:
    repo: "https://github.com/pearofducks/ansible-vim.git"
    dest: "{{ vim_dir }}/pack/others/start/ansible-vim"
    update: yes

- name: Git clone https://github.com/vim-syntastic/syntastic.git
  ansible.builtin.git:
    repo: "https://github.com/vim-syntastic/syntastic.git"
    dest: "{{ vim_dir }}/pack/others/start/syntastic"
    update: yes

- name: Git clone https://github.com/fatih/vim-go.git
  ansible.builtin.git:
    repo: "https://github.com/fatih/vim-go.git"
    dest: "{{ vim_dir }}/pack/others/start/vim-go"
    update: yes

- name: Git clone https://github.com/simnalamburt/vim-mundo.git
  ansible.builtin.git:
    repo: "https://github.com/simnalamburt/vim-mundo.git"
    dest: "{{ vim_dir }}/pack/others/start/vim-mundo"
    update: yes

- name: Git clone https://github.com/lambdalisue/fern.vim.git
  ansible.builtin.git:
    repo: "https://github.com/lambdalisue/fern.vim.git"
    dest: "{{ vim_dir }}/pack/others/start/fern.vim"
    update: yes

- name: Git clone https://github.com/lambdalisue/fern-hijack.vim.git
  ansible.builtin.git:
    repo: "https://github.com/lambdalisue/fern-hijack.vim.git"
    dest: "{{ vim_dir }}/pack/others/start/fern-hijack.vim"
    update: yes

- name: Git clone https://github.com/lambdalisue/fern-git-status.vim.git
  ansible.builtin.git:
    repo: "https://github.com/lambdalisue/fern-git-status.vim.git"
    dest: "{{ vim_dir }}/pack/others/start/fern-git-status.vim"
    update: yes

- name: Git clone https://github.com/tpope/vim-commentary.git
  ansible.builtin.git:
    repo: "https://github.com/tpope/vim-commentary.git"
    dest: "{{ vim_dir }}/pack/others/start/vim-commentary"
    update: yes

- name: Git clone https://github.com/tpope/vim-endwise.git
  ansible.builtin.git:
    repo: "https://github.com/tpope/vim-endwise.git"
    dest: "{{ vim_dir }}/pack/others/start/vim-endwise"
    update: yes

- name: Git clone https://github.com/tpope/vim-repeat.git
  ansible.builtin.git:
    repo: "https://github.com/tpope/vim-repeat.git"
    dest: "{{ vim_dir }}/pack/others/start/vim-repeat"
    update: yes

- name: Git clone https://github.com/tpope/vim-speeddating.git
  ansible.builtin.git:
    repo: "https://github.com/tpope/vim-speeddating.git"
    dest: "{{ vim_dir }}/pack/others/start/vim-speeddating"
    update: yes

- name: Git clone https://github.com/tpope/vim-surround.git
  ansible.builtin.git:
    repo: "https://github.com/tpope/vim-surround.git"
    dest: "{{ vim_dir }}/pack/others/start/vim-surround"
    update: yes
