---
- name: Create directory {{ projects_dir }}
  ansible.builtin.file:
    path: "{{ projects_dir }}"
    state: directory

- name: Git clone/pull Dot-Files and Vim colorscheme
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ projects_dir }}/{{ item.name }}"
    update: yes
  loop:
    - name: Dot-Files
      url: "{{ git_url_dotfiles }}"
    - name: Static-Color-Scheme
      url: "{{ git_url_staticcolorscheme }}"
#    - name: electricboogaloo.vim
#      url: "{{ git_url_electricboogaloo }}"

- name: Create directories under {{ vim_dir }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ vim_dir }}"
    - "{{ vim_dir }}/backup"
    - "{{ vim_dir }}/swap"
    - "{{ vim_dir }}/undo"
    - "{{ vim_dir }}/pack/ggustafsson/start"
    - "{{ vim_dir }}/pack/others/start"

- name: Create symbolic links to Dot-Files and Vim colorscheme
  ansible.builtin.file:
    src: "{{ projects_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: Dot-Files/vimrc
      dest: "{{ ansible_env.HOME }}/.vimrc"
    - src: Dot-Files/vim/after
      dest: "{{ vim_dir }}/after"
    - src: Dot-Files/vim/templates
      dest: "{{ vim_dir }}/templates"
    - src: Static-Color-Scheme
      dest: "{{ vim_dir }}/pack/ggustafsson/start/Static-Color-Scheme"
#    - src: electricboogaloo.vim
#      dest: "{{ vim_dir }}/pack/ggustafsson/start/electricboogaloo.vim"

- name: Git clone/pull misc Vim plugins
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ vim_dir }}/pack/others/start/{{ item.name }}"
    update: yes
  loop:
    - name: ansible-vim
      url: https://github.com/pearofducks/ansible-vim.git
    - name: syntastic
      url: https://github.com/vim-syntastic/syntastic.git
    - name: vim-go.git
      url: https://github.com/fatih/vim-go.git
    - name: vim-mundo.git
      url: https://github.com/simnalamburt/vim-mundo.git
    - name: fern.vim.git
      url: https://github.com/lambdalisue/fern.vim.git
    - name: fern-hijack.vim.git
      url: https://github.com/lambdalisue/fern-hijack.vim.git
    - name: fern-git-status.vim.git
      url: https://github.com/lambdalisue/fern-git-status.vim.git
    - name: vim-commentary.git
      url: https://github.com/tpope/vim-commentary.git
    - name: vim-endwise.git
      url: https://github.com/tpope/vim-endwise.git
    - name: vim-repeat.git
      url: https://github.com/tpope/vim-repeat.git
    - name: vim-speeddating.git
      url: https://github.com/tpope/vim-speeddating.git
    - name: vim-surround.git
      url: https://github.com/tpope/vim-surround.git
